### ISSUE TITLE
Incorrect dependency sklearn instead of scikit-learn

### ISSUE THREAD

**Issue by jaydosi** [rinziv/LORE_ext#16]
Back in Feb 19, 2020 the requirement.txt contains the correct dependency: scikit-learn==0.22.1
https://github.com/rinziv/LORE_ext/commit/2ce7b75fc813af8c49b39ab6bd8556a3b9e0d6d4

After the refactoring in May 11, 2022 in pyproject.toml the dependency became incorrect: sklearn
https://github.com/rinziv/LORE_ext/commit/2e08c3570c834ef0cb6bb0385e552a5af21f1515

This is still incorrect in the current files requirement.txt and setup.cfg.

See also https://pypi.org/project/sklearn/

**Comment by rinziv** [comment]
Fixed the dependency on the requirements file.
New version available on the PyPi repository (v1.0.1)
