### ISSUE TITLE
Errore durante l'installazione

### ISSUE THREAD

**Issue by pellungrobe** [rinziv/LORE_ext#18]
Collecting LORE-ext
  Using cached LORE_ext-0.2-py3-none-any.whl (19 kB)
Requirement already satisfied: numpy in /Users/roberto/anaconda3/envs/xailibenv/lib/python3.12/site-packages (from LORE-ext) (1.26.3)
Collecting pandas (from LORE-ext)
  Using cached pandas-2.1.4-cp312-cp312-macosx_11_0_arm64.whl.metadata (18 kB)
Collecting deap>=1.3.1 (from LORE-ext)
  Using cached deap-1.4.1.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
Collecting pillow (from LORE-ext)
  Using cached pillow-10.2.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (9.7 kB)
Requirement already satisfied: scipy in /Users/roberto/anaconda3/envs/xailibenv/lib/python3.12/site-packages (from LORE-ext) (1.11.4)
Collecting sklearn (from LORE-ext)
  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by rinziv** [comment]
The problem was due to an old deprecated dependency.
The new version v1.0.1 available also on PyPi fixes this issues
